set_property IOSTANDARD LVCMOS33 [get_ports {mclk[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mclk[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sclk[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sclk[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ws[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ws[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports reset_n]
set_property IOSTANDARD LVCMOS33 [get_ports filter_on_n]
set_property IOSTANDARD LVCMOS33 [get_ports sd_rx]
set_property IOSTANDARD LVCMOS33 [get_ports sd_tx]
set_property PACKAGE_PIN V17 [get_ports reset_n]
set_property PACKAGE_PIN V16 [get_ports filter_on_n]
set_property PACKAGE_PIN G3 [get_ports sd_rx]
set_property PACKAGE_PIN G2 [get_ports sd_tx]
set_property PACKAGE_PIN J1 [get_ports {mclk[1]}]
set_property PACKAGE_PIN H1 [get_ports {mclk[0]}]
set_property PACKAGE_PIN J2 [get_ports {sclk[1]}]
set_property PACKAGE_PIN H2 [get_ports {sclk[0]}]
set_property PACKAGE_PIN L2 [get_ports {ws[1]}]
set_property PACKAGE_PIN K2 [get_ports {ws[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property PACKAGE_PIN W5 [get_ports clock]
